apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "ncqakubnet"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "ncqakubnet"
    spec:
      containers:
        - name: "ncqakubnet"
          image: "ncqacontainerlab.azurecr.io/ncqakubnet"
          ports:
          - containerPort: 443