apiVersion: v1
kind: Service
metadata:
    name: "ncqakubnet"
    labels:
        app: "ncqakubnet"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "ncqakubnet"